import { Grid } from '@mui/material'
import axios from 'axios'
import Head from 'next/head'
import BlogCard from '../src/components/card'
import styles from '../styles/Home.module.css'
import {getAllBlogs} from '../src/services/blog'
export default function Home({blogs}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container spacing={2}>
          {blogs?.map((item, index) => (
            <Grid item key={index} lg={3} md={3} sm={6} xs={12}>
              <BlogCard item={item} />
            </Grid>
          ))}
        </Grid>
      </main>
    </>
  )
}

export async function getServerSideProps(){
 const res = await getAllBlogs();
 if(!res.status){
  return {
    props:{
      blogs:[]
    }
  }
 } 
 return {
  props:{
    blogs:res.data
  }
 }
}
