import { Grid } from '@mui/material'
import Head from 'next/head'
import BlogCard from '../src/components/card'
import styles from '../styles/Home.module.css'

export default function Home() {
  const cards = [
    {
      id: "1",
      title: 'food',
      description: 'about food which is good for human health',
      img: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg'
    },
    {
      id: "2",
      title: 'Burger',
      description: 'burger is a fastfood so it is not good for human health',
      img: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    },
    {
      id: "3",
      title: 'food',
      description: 'about food which is good for human health',
      img: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg'
    },
    {
      id: "4",
      title: 'Burger',
      description: 'burger is a fastfood so it is not good for human health',
      img: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    },
    {
      id: "5",
      title: 'food',
      description: 'about food which is good for human health',
      img: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg'
    },
    {
      id: "6",
      title: 'Burger',
      description: 'burger is a fastfood so it is not good for human health',
      img: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    },
    {
      id: "7",
      title: 'food',
      description: 'about food which is good for human health',
      img: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg'
    },
    {
      id: "8",
      title: 'Burger',
      description: 'burger is a fastfood so it is not good for human health',
      img: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
    }
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container spacing={2}>
          {cards.map((item, index) => (
            <Grid item key={index} lg={3} md={3} sm={6} xs={12}>
              <BlogCard item={item} />
            </Grid>
          ))}
        </Grid>
      </main>
    </>
  )
}
